name: Lint

on: [pull_request, push]

jobs:
  lint:
    needs: [changes]
    name: Prettier Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Setup NodeJS
        uses: ./.github/actions/setup-nodejs
      - name: Run prettier check
        run: pnpm prettier:check
